modLoader="javafml" #mandatory
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
# The license for you mod. This is mandatory metadata and allows for easier comprehension of your redistributive properties.
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license="BSD 3-Clause License"
issueTrackerURL="https://github.com/RealYusufIsmail/Ben-10-Mod/issues" #optional
[[mods]]
modId="bentenmod"
version="${file.jarVersion}"
displayName="Ben10 Mod"
displayURL="https://realyusufismail.github.io/Ben-10-Mod/recipes.html" #optional
logoFile="headerimg.png"
credits="Ben10 mob mod by Yusuf Ismail. PierogiP for drawing some of the items in the mod and gentworm for helping me with my code."

authors="Yusuf Ismail and gentworm" #optional
description='''
A mod which adds Villains, heroes and armour and items from the Ben 10 series. Some Vilans will be added and a lot of items and armour will be added. The omnitrix will be added
soon.
Dont not copy my mod.
made by Yusuf Ismail.
Github is https://github.com/realyusufismail
join discord for support and teasers https://discord.gg/g858J6q
PierogiP: https://www.curseforge.com/members/polisch_pierogi/
gentworm: https://www.curseforge.com/members/gentworm/followers
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.bentenmod]] #optional

modId="forge"
mandatory=true
versionRange="[36,)"
ordering="NONE"
side="BOTH"
[[dependencies.bentenmod]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5,)"
ordering="NONE"
side="BOTH"

[[dependencies.bentenmod]]
modId="patchouli"
mandatory=true
versionRange="[1.16.4-50,)"
ordering="NONE"
side="BOTH"

